"""Static file templates for generated projects — deterministic, no LLM."""

STATIC_DIRS = ("data/raw", "data/processed", "notebooks", "reports/figures", "logs")

GITIGNORE = """\
__pycache__/
*.pyc
*.egg-info/
.venv/
data/raw/*
!data/raw/.gitkeep
data/processed/*
!data/processed/.gitkeep
logs/*
!logs/.gitkeep
"""

PYPROJECT = """\
[project]
name = "{name}"
version = "0.1.0"
description = "Reproduction scaffold generated by paperdigest"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
dev = ["pytest>=8"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/{name}"]

[tool.pytest.ini_options]
testpaths = ["tests"]
"""

TRACKING_PY = '''\
"""Zero-dependency experiment tracking: JSONL run records + per-run log files."""
from __future__ import annotations

import datetime
import json
import logging
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RUNS_FILE = ROOT / "experiments" / "runs.jsonl"
LOG_DIR = ROOT / "logs"


def log_run(params: dict, metrics: dict, **meta) -> str:
    """Append one run record to experiments/runs.jsonl and return its run id."""
    run_id = datetime.datetime.now().strftime("%Y%m%d-%H%M%S-") + uuid.uuid4().hex[:6]
    record = {
        "run_id": run_id,
        "timestamp": datetime.datetime.now().isoformat(timespec="seconds"),
        "params": params,
        "metrics": metrics,
        **meta,
    }
    RUNS_FILE.parent.mkdir(parents=True, exist_ok=True)
    with RUNS_FILE.open("a") as f:
        f.write(json.dumps(record) + "\\n")
    return run_id


def get_logger(name: str, run_id: str = "adhoc") -> logging.Logger:
    """Logger writing to stderr and logs/<run_id>.log."""
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    logger = logging.getLogger(name)
    if not logger.handlers:
        logger.setLevel(logging.INFO)
        fmt = logging.Formatter("%(asctime)s %(levelname)s %(name)s: %(message)s")
        for handler in (logging.StreamHandler(), logging.FileHandler(LOG_DIR / f"{run_id}.log")):
            handler.setFormatter(fmt)
            logger.addHandler(handler)
    return logger
'''
